apiVersion: v1
kind: Namespace
metadata:
  name: flask

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-deployment
  namespace: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      namespace: flask
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: flaskdockerrepo
        image: githubactionacrprac.azurecr.io/flask-new:${{ github.sha }}
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-svc
  namespace: flask
spec:
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
